### ISSUE TITLE
This is still generating services on multiple ports

### ISSUE THREAD

**Issue by akshay-nm** [edis/sls-multi-gateways#2]
I have my services in ./admin dir. 
Here is my `sls-multi-gateways.yml`:
```yml
port: 5000
stage: v0
services:
  - srvName: admin-docs
    srvPath: docs
    srvSource: ./admin/docs
  - srvName: admin-sessions
    srvPath: sessions
    srvSource: ./admin/sessions
```

The services are being generated on:
http://localhost:5000
http://localhost:5001 

Logs: 
```
yarn run v1.22.10
$ sls-multi-gateways
[HPM] Proxy created: /  -> http://localhost:5000/v0/
[HPM] Proxy created: /  -> http://localhost:5001/v0/
```
The sessions and docs service are not accessible on same port aka 5000.
